# SELECT SUB1.FISH_COUNT AS FISH_COUNT, SUB2.FISH_NAME AS FISH_NAME
# FROM
# (
# SELECT COUNT(ID) AS FISH_COUNT, FISH_TYPE
# FROM FISH_INFO
# GROUP BY FISH_TYPE
# ) AS SUB1
# INNER JOIN FISH_NAME_INFO AS SUB2
# ON SUB1.FISH_TYPE = SUB2.FISH_TYPE
# ORDER BY SUB1.FISH_COUNT DESC

SELECT COUNT(SUB1.ID) AS FISH_COUNT, SUB2.FISH_NAME
FROM
(
FISH_INFO AS SUB1
INNER JOIN FISH_NAME_INFO AS SUB2
ON SUB1.FISH_TYPE = SUB2.FISH_TYPE
)
GROUP BY SUB2.FISH_NAME
ORDER BY FISH_COUNT DESC
