# SELECT CAR_ID,
# CASE WHEN DATEDIFF('2022-10-16', MAX_DATE) >= 0 THEN '대여 가능'
# ELSE '대여중' END AS AVAILABILITY
# FROM
# (SELECT DISTINCT CAR_ID,
# MAX(END_DATE) AS MAX_DATE
# FROM
# (SELECT CAR_ID, MAX(START_DATE) AS START_DATE, MAX(END_DATE) AS END_DATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE DATEDIFF('2022-10-16', START_DATE) >= 0
# GROUP BY CAR_ID) AS SUBQUERY_FIRST
# GROUP BY CAR_ID) AS SUBQUERY_SECOND
# ORDER BY CAR_ID DESC

SELECT CAR_ID,
CASE WHEN DATEDIFF('2022-10-16', END_DATE) > 0 THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY
FROM
(SELECT CAR_ID, MAX(START_DATE) AS START_DATE, MAX(END_DATE) AS END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATEDIFF('2022-10-16', START_DATE) >= 0
GROUP BY CAR_ID) AS SUBQUERY
ORDER BY CAR_ID DESC;